### PR TITLE
Migrated to work in VS2017

### PR DESCRIPTION
**Pull request by TheMrAnderson**
I have migrated the solution from VS2010 format to VS2017 as well as made the VSIX work in VS2017.  Also cleaned up the backup files

### CODE REVIEW

**Comment by latish** [comment]
Thanks! I don't work in VS much myself nowadays, but I have merged your commit. I am sure other devs would appreciate it.

**Comment by TheMrAnderson** [comment]
Wow!  That was a fast merge.  All of use use this at work and this was the
only extension that didn't work with VS2017 yet.  Thank you for what you
have created.

**Comment by TheMrAnderson** [comment]
When are you planning on publishing this update to the marketplace?

**Comment by latish** [comment]
To be honest, I don't even remember the credentials to log into for updating the extension. You are welcome to publish the extension update yourself.

**Pull request merged**
